import "dotenv/config";

const config = {
  TEST_MODE: true,
  MONGO_URI: process.env.MONGO_URI,
  REDIS_URL: process.env.REDIS_URL || "redis://127.0.0.1:6379",
  CACHE_TTL_SECONDS: 6 * 60 * 60,
  CRON_SCHEDULE: process.env.CRON_SCHEDULE || "*/1 * * * *",
  PUBLER: {
        API_KEY: process.env.PUBLER_API_KEY,
        WORKSPACE_ID: process.env.PUBLER_WORKSPACE_ID,
        ACCOUNTS: process.env.PUBLER_ACCOUNTS 
            ? process.env.PUBLER_ACCOUNTS.split(',').map(a => a.trim())
            : ['6778626ce77c42842c59202e','6901e01d1a1afe47aedde520'], 
    },
  EMAIL: {
    HOST: process.env.EMAIL_HOST,
    PORT: process.env.EMAIL_PORT,
    SECURE: process.env.EMAIL_SECURE === "true",
    USER: process.env.EMAIL_USER,
    PASS: process.env.EMAIL_PASS,
    TO: process.env.EMAIL_TO,
  },
  AMAZON: {
    ACCESS_KEY: process.env.AMAZON_ACCESS_KEY,
    SECRET_KEY: process.env.AMAZON_SECRET_KEY,
    PARTNER_TAG: process.env.AMAZON_PARTNER_TAG,
    MARKETPLACE: process.env.AMAZON_MARKETPLACE || "www.amazon.com",
    RESOURCES: [
      "Images.Primary.Large",
      "ItemInfo.Title",
      "Offers.Listings.Price",
      "Offers.Listings.SavingBasis",
    ],
    CATEGORIES: [
      "Apparel",
      "Appliances",
      "Automotive",
      "Baby",
      "Beauty",
      "Books",
      "Collectibles",
      "Computers",
      "Electronics",
      "EverythingElse",
      "Fashion",
      "Furniture",
      "GardenAndOutdoor",
      "GiftCards",
      "GroceryAndGourmetFood",
      "HealthPersonalCare",
      "HomeAndKitchen",
      "Industrial",
      "Jewelry",
      "KindleStore",
      "Luggage",
      "LuxuryBeauty",
      "MobileApps",
      "MoviesAndTV",
      "Music",
      "MusicalInstruments",
      "OfficeProducts",
      "PetSupplies",
      "Shoes",
      "Software",
      "SportsAndOutdoors",
      "ToolsAndHomeImprovement",
      "ToysAndGames",
      "VideoGames",
      "Watches",
    ],
    ITEM_COUNT: 20,
  },
};

export default config;
